apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-t3ec
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-t3ec
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-t3ec
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-t3ec
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-t3ec
    spec:
      containers:
      - image: quay.io/mbasti-test-org/happy-depl-kpno-tenant/appstudio/dc-metro-map-t3ec@sha256:79b25c45edaf55f88374136f57365dbe780af2df5739b26c6c760d3aadc557b4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
